{
 "title": "Moscow Temperature",
 "time": { "from": "now-2h", "to": "2019-05-22T16:51:29.000Z" },
 "panels": [
  {
   "title": "Current",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    { "target": "temperatures.current" }
   ]
  },
  {
   "title": "2 hour mean forecast error",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 0 },
   "targets": [
    {
     "target": "timeSlice(multiplySeries(absolute(diffSeries(temperatures.current, timeShift(temperatures.2h, '2h', false, false))), isNonNull(temperatures.current), isNonNull(timeShift(temperatures.2h, '2h', false, false))), 'now-2h', 'now')"
    }
   ]
  },
  {
   "title": "As is",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(movingWindow(temperatures.current, '20sec', 'last'))"
    },
    {
     "target": "alias(movingWindow(temperatures.1h, '20sec', 'last'), '+1h')"
    },
    {
     "target": "alias(movingWindow(temperatures.2h, '20sec', 'last'), '+2h')"
    }
   ]
  },
  {
   "title": "Aligned",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(movingWindow(temperatures.current, '20sec', 'last'))"
    },
    {
     "target": "alias(movingWindow(timeShift(temperatures.1h, '1h', false, false), '20sec', 'last'), '+1h')"
    },
    {
     "target": "alias(timeShift(movingWindow(temperatures.2h, '20sec', 'last'), '2h', false, false), '+2h')"
    }
   ]
  }
 ]
}